---
abstract: 'Mojolicious::Lite webapp that lets you search (with regexp) and display CPAN modules documentation'
author:
  - 'Ahmad Syaltut <Isyaltut@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perldolicious
provides:
  App::perldolicious:
    file: lib/App/perldolicious.pm
    version: 0.001
requires:
  IO::Zlib: 0
  Module::CoreList: 0
  Mojolicious: 0
  Pod::Cpandoc: 0
resources:
  homepage: https://github.com/Syaltut/perl-App-perldolicicous
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Syaltut/perl-App-perldolicicous.git
version: 0.001
